version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 20
    target-branch: master
    versioning-strategy: increase
    commit-message:
      prefix: '[skip netlify]'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: master
    commit-message:
      prefix: '[skip netlify]'
