version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '00:00'
      timezone: 'America/Sao_Paulo'
    open-pull-requests-limit: 50
    versioning-strategy: increase
    commit-message:
      prefix: '⬆️ [skip ci]'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '00:00'
      timezone: 'America/Sao_Paulo'
    commit-message:
      prefix: '⬆️ [skip ci]'
