name: Deploy
on:
  schedule:
    - cron: '0 7 * * 2'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to netlify
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
